package org.hexgame.ui;

import org.hexgame.core.*;
import org.hexgame.controllers.GuiGameController;
import javax.swing.*;
import java.awt.event.*;

public class HexGui extends javax.swing.JFrame  {
  GuiGameController controller;

  /** Creates new form HexGui */
  public HexGui(GuiGameController _controller) {
    controller = _controller;
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initHexboard(int size){

    hexboard= new Hexboard(size);
    GroupLayout hexboardLayout = new GroupLayout(hexboard);
    hexboard.setLayout(hexboardLayout);
    hexboardLayout.setHorizontalGroup(
        hexboardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGap(0, 460, Short.MAX_VALUE)
        );
    hexboardLayout.setVerticalGroup(
        hexboardLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGap(0, 496, Short.MAX_VALUE)
        );

    GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addComponent(hexboard, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    layout.setVerticalGroup(
        layout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addComponent(hexboard, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
  }

  private void initComponents() {

    jFrame1 = new JFrame();
    jButton1 = new JButton();
    jSpinner1 = new JSpinner(new SpinnerNumberModel(11, 0, 11, 1));
    jLabel1 = new JLabel();
    jMenuBar1 = new JMenuBar();
    jMenu1 = new JMenu();
    jMenuItem1 = new JMenuItem();
    jMenuItem2 = new JMenuItem();
    jMenu2 = new JMenu();
    jMenuItem3 = new JMenuItem();
    jMenuItem4 = new JMenuItem();
    initHexboard(11);

    jButton1.setText("OK !");
    jButton1.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jSpinner1.addMouseListener(new MouseAdapter() {
      public void mousePressed(MouseEvent evt) {
        jSpinner1MousePressed(evt);
      }
    });

    jLabel1.setText("size of map");

    javax.swing.GroupLayout jFrame1Layout = new GroupLayout(jFrame1.getContentPane());
    jFrame1.getContentPane().setLayout(jFrame1Layout);
    jFrame1Layout.setHorizontalGroup(
        jFrame1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
          .addGap(61, 61, 61)
          .addComponent(jSpinner1, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
          .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
          .addGroup(jFrame1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
              .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
              .addComponent(jButton1)
              .addGap(36, 36, 36))
            .addGroup(jFrame1Layout.createSequentialGroup()
              .addGap(50, 50, 50)
              .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE)
              .addContainerGap())))
        );
    jFrame1Layout.setVerticalGroup(
        jFrame1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(jFrame1Layout.createSequentialGroup()
          .addContainerGap()
          .addGroup(jFrame1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
            .addComponent(jSpinner1, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1))
          .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
          .addComponent(jButton1)
          .addContainerGap())
        );

    setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    setTitle("Hex Game");
    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

    jMenu1.setText("File");

    jMenuItem1.setText("New Game");
    jMenuItem1.addMouseListener(new MouseAdapter() {
      public void mousePressed(MouseEvent evt) {
        jMenuItem1MousePressed(evt);
      }
    });
    jMenu1.add(jMenuItem1);

    jMenuItem2.setText("Exit");
    jMenuItem2.addMouseListener(new MouseAdapter() {
      public void mousePressed(MouseEvent evt) {
        jMenuItem2MousePressed(evt);
      }
    });
    jMenu1.add(jMenuItem2);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Edit");

    jMenuItem3.setText("Preferences");
    jMenuItem3.addMouseListener(new MouseAdapter() {
      public void mousePressed(MouseEvent evt) {
        jMenuItem3MousePressed(evt);
      }
    });
    jMenu2.add(jMenuItem3);

    jMenuItem4.setText("Undo");
    jMenuItem4.addMouseListener(new MouseAdapter() {
      public void mousePressed(MouseEvent evt) {
        jMenuItem4MousePressed(evt);
      }
    });
    jMenu2.add(jMenuItem4);

    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jMenuItem1MousePressed(MouseEvent evt) {//event New Game
    hexboard.setVisible(false);
    SpinnerNumberModel model = (SpinnerNumberModel)jSpinner1.getModel();
    int value = model.getNumber().intValue();
    initHexboard(value);
  }

  private void jMenuItem2MousePressed(MouseEvent evt) {//event Exit

    System.exit(0);
  }//

  private void jMenuItem3MousePressed(MouseEvent evt) {//event Preferences
    jFrame1.pack();
    jFrame1.setVisible(true);
  }//

  private void jMenuItem4MousePressed(MouseEvent evt) {//event Undo
    //cofanie ruchu
  }//

  private void jButton1ActionPerformed(ActionEvent evt) {//event OK!

    jFrame1.setVisible(false);
  }//

  private void jSpinner1MousePressed(MouseEvent evt) {//GEN-FIRST:event_jSpinner1MouseClicked
    // TODO add your handling code here:
  }//GEN-LAST:event_jSpinner1MouseClicked

  /**
   * @param args the command line arguments
   */
  public static void start(GuiGameController _controller) {
    final GuiGameController controller = _controller;
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        HexGui hex = new HexGui(controller);
        hex.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JButton jButton1;
  private JFrame jFrame1;
  private JLabel jLabel1;
  private JMenu jMenu1;
  private JMenu jMenu2;
  private JMenuBar jMenuBar1;
  private JMenuItem jMenuItem1;
  private JMenuItem jMenuItem2;
  private JMenuItem jMenuItem3;
  private JMenuItem jMenuItem4;
  private JSpinner jSpinner1;
  private Hexboard hexboard;
  // End of variables declaration//GEN-END:variables

}
